language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- chmod +x ./gradlew
- chmod +x ./gradlew.bat
install: "./gradlew assemble"
script: "./gradlew check"
cache:
  directories:
  - "$HOME/.gradle/caches/"
deploy:
  provider: script
  script: "./gradlew publish --info --no-daemon -P repoPassword=$REPO_PASSWORD"
  skip_cleanup: true
  on:
    branch: master
    jdk: openjdk8